open-cluster-management-io/policy-generator-plugin

internal/plugin.go

This is to address a comment left here:
https://github.com/open-cluster-management/policy-generator-plugin/pull/2#pullrequestreview-750674862

Use a package-level default variable to contain all policy defaults

---

internal/plugin.go
internal/plugin_test.go

In order to know what to call the common placement rule, the new fields of
policyDefaults.placement.name and policies[0].placement.name are added.
If neither of these are set, then no placement rule consolidation will
occur.
Additionally, this now checks for duplicate placement rule names and
returns an error when that occurs.

Consolidate placement rules based on cluster selectors

---

docs/policygenerator.md
internal/expanders/gatekeeper_test.go

This addresses the comments from #12 since Dale is out today and thus is not able to address the feedback.

Address comments from #12

---

docs/policygenerator-reference.yaml
internal/plugin.go
internal/plugin_test.go
internal/types/types.go
internal/utils.go
internal/utils_test.go

Signed-off-by: Chunxi Luo chuluo@redhat.com

Add-option-to-not-consolidate-under-single-ConfigurationPolicy-#15836

---

Makefile
README.md

This excludes instructions for Windows since I don't have a Windows machine handy to test it.

Document how to build and install for a GitHub release

---

.gitignore
build/common/config/.golangci.yml
internal/plugin.go
internal/plugin_test.go

Add .idea path to gitignore
Signed-off-by: melserngawy <melserng@redhat.com>

Add clusterSelector exist operator for empty key value

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
SECURITY.md
build/common/Makefile.common.mk
cmd/main.go
go.mod
internal/expanders/expanders.go
internal/expanders/gatekeeper.go
internal/expanders/gatekeeper_test.go
internal/expanders/kyverno.go
internal/expanders/kyverno_test.go
internal/plugin.go
internal/plugin_config_test.go
internal/plugin_test.go
internal/utils.go
internal/utils_test.go

- https://github.com/stolostron/backlog/issues/17978

Organization rename to `stolostron`

---

docs/policygenerator-reference.yaml
internal/plugin.go
internal/plugin_config_test.go
internal/plugin_test.go
internal/types/types.go
internal/utils.go

Relates:
https://github.com/stolostron/backlog/issues/20030

Add support for the evaluation intervals

---

internal/plugin.go
internal/plugin_test.go

https://github.com/stolostron/backlog/issues/20475

Change PolicySet API version to v1beta1

---

OWNERS

Remove user that is no longer an owner
Refs:
- https://github.com/stolostron/backlog/issues/21546
Signed-off-by: Gus Parvin <gparvin@redhat.com>

Update the owners file

---

docs/policygenerator-reference.yaml
internal/plugin.go
internal/plugin_test.go
internal/types/types.go

Signed-off-by: melserngawy <melserng@redhat.com>

Allow adding policy annotations

---

internal/utils.go
internal/utils_test.go

Addresses:
- https://github.com/stolostron/backlog/issues/22787

Ignore nil YAML

---

docs/policygenerator-reference.yaml
internal/plugin.go
internal/plugin_test.go
internal/types/types.go
internal/utils.go
internal/utils_test.go

This will allow users to disable policy templating on generated
configuration policies.
Relates:
https://github.com/stolostron/backlog/issues/23078

Add support for setting the configuration policy annotations

---

.github/workflows/linters.yml
.github/workflows/unit-tests.yml
.gitignore
Makefile
build/common/config/.golangci.yml
cmd/main.go
go.mod
go.sum
internal/expanders/expanders_utils_test.go
internal/expanders/gatekeeper_test.go
internal/expanders/kyverno_test.go
internal/patches.go
internal/patches_test.go
internal/plugin.go
internal/plugin_config_test.go
internal/plugin_test.go
internal/utils.go
internal/utils_test.go

This also applies the linting rules standardized by the Policy SIG.
Relates:
https://github.com/stolostron/backlog/issues/24763

Update to Go 1.18

---

Makefile.prow
sonar-project.properties

Connected Prow PR:
- https://github.com/openshift/release/pull/31040

Add Prow/Sonar configurations

---

cmd/main.go
internal/patches.go
internal/utils.go

Address `gosec` vulnerabilities

nosec gosec

---

docs/policygenerator-reference.yaml
internal/plugin.go
internal/plugin_test.go
internal/types/types.go
internal/utils.go
internal/utils_test.go

I wrote a grotesquely monstrous custom NamespaceSelector comparison tool for the tests. Not sure if there was a better way to do that?
Addresses:
- https://github.com/stolostron/backlog/issues/25135

Add LabelSelector to NamespaceSelector

---

internal/plugin.go
internal/plugin_config_test.go
internal/plugin_test.go

Signed-off-by: Will Kutler <wkutler@redhat.com>
https://github.com/stolostron/backlog/issues/17598

validate resource names for dns compliance

---

cmd/main.go
docs/policygenerator-reference.yaml
docs/policygenerator.md
examples/input-kustomize/base/kustomization.yaml
examples/input-kustomize/base/nginx-pod.yaml
examples/input-kustomize/dev/kustomization.yml
examples/input-kustomize/kustomization.yml
examples/input-kustomize/prod/kustomization.yml
examples/kustomization.yml
examples/policyGenerator-kustomize.yaml
internal/utils.go
internal/utils_test.go

Addresses:
- https://github.com/stolostron/backlog/issues/25290

Support Kustomize directories

---

.github/workflows/linters.yml
.github/workflows/unit-tests.yml

This is in preparation to create `vx.y` release branches.

Add release branches to workflows

---

internal/plugin.go
internal/plugin_test.go
internal/utils.go
internal/utils_test.go

Signed-off-by: Tao Liu <tali@redhat.com>

OCPBUGS-2200: Add remediationAction at the Policy spec level

---

docs/policygenerator-reference.yaml
internal/patches_test.go
internal/plugin.go
internal/plugin_test.go
internal/types/types.go

Relates:
https://issues.redhat.com/browse/ACM-1690

Add support for the copyPolicyMetadata field

---

.gitignore
Makefile
README.md
build/common/config/.golangci.yml
cmd/PolicyGenerator/main.go
go.mod
internal/expanders/expanders.go
internal/expanders/gatekeeper.go
internal/expanders/gatekeeper_test.go
internal/expanders/kyverno.go
internal/expanders/kyverno_test.go
internal/plugin.go
internal/plugin_config_test.go
internal/plugin_test.go
internal/utils.go
internal/utils_test.go

ref: https://issues.redhat.com/browse/ACM-2598
Followup to:
- #88

Fix `go install` and module path

---

docs/policygenerator-reference.yaml
docs/policygenerator.md
examples/policyGenerator.yaml

- Add PlacementRule deprecation notes
- Fix incorrect labelSelector/clusterSelector references

Fix placement doc

---

.github/workflows/release.yml

Bump `action-gh-release` version

---

examples/input-kustomize/base/kustomization.yaml
examples/input-kustomize/dev/kustomization.yml
examples/input-kustomize/kustomization.yml
examples/input-kustomize/prod/kustomization.yml
examples/kustomization.yml
internal/patches.go
internal/patches_test.go
internal/plugin.go

Also makes `MatchExpression` order deterministic
ref: https://issues.redhat.com/browse/ACM-8984

Fix `PatchesStrategicMerge` deprecation warning

---

.github/workflows/unit-tests.yml
docs/policygenerator.md
examples/input/placementrule.yaml
examples/policyGenerator-kustomize.yaml
examples/policyGenerator.yaml
internal/plugin.go
internal/plugin_test.go
internal/testdata/ordering/default-deps-propagated.yaml
internal/testdata/ordering/default-extradeps-consolidated.yaml
internal/testdata/ordering/default-extradeps-override.yaml
internal/testdata/ordering/default-extradeps-propagated.yaml
internal/testdata/ordering/dependency-details-config.yaml
internal/testdata/ordering/extradeps-overrides.yaml
internal/testdata/ordering/ignore-pending-manifest-override.yaml
internal/testdata/ordering/ignore-pending-policy-consolidated.yaml
internal/testdata/ordering/ignore-pending-policy-override.yaml
internal/testdata/ordering/ignore-pending-propagation.yaml
internal/testdata/ordering/manifest-extradeps-configpolicy.yaml
internal/testdata/ordering/manifest-extradeps.yaml
internal/testdata/ordering/one-ordered-policy.yaml
internal/testdata/ordering/override-dependencies.yaml
internal/testdata/ordering/policy-extradeps.yaml
internal/testdata/ordering/policy-level-dependencies.yaml
internal/testdata/ordering/three-ordered-manifests.yaml
internal/testdata/ordering/two-ordered-policies.yaml

`PlacementRule` is deprecated
ref: https://issues.redhat.com/browse/ACM-1286

Make `Placement` the default

---

docs/policygenerator-reference.yaml
internal/plugin.go
internal/plugin_test.go
internal/types/types.go

Allows setting custom labels on the generated policy.  
https://issues.redhat.com/browse/ACM-9000

Add field to set labels on the Policy generated

---

docs/policygenerator-reference.yaml
internal/plugin.go
internal/plugin_test.go
internal/types/types.go
internal/utils.go
internal/utils_test.go

ref: https://issues.redhat.com/browse/ACM-9088

Add `recordDiff` to policy generator

---

internal/plugin.go
internal/plugin_test.go
internal/testdata/ordering/default-deps-propagated.yaml
internal/testdata/ordering/default-extradeps-consolidated.yaml
internal/testdata/ordering/default-extradeps-override.yaml
internal/testdata/ordering/default-extradeps-propagated.yaml
internal/testdata/ordering/dependency-details-config.yaml
internal/testdata/ordering/extradeps-overrides.yaml
internal/testdata/ordering/ignore-pending-manifest-override.yaml
internal/testdata/ordering/ignore-pending-policy-consolidated.yaml
internal/testdata/ordering/ignore-pending-policy-override.yaml
internal/testdata/ordering/ignore-pending-propagation.yaml
internal/testdata/ordering/manifest-extradeps-configpolicy.yaml
internal/testdata/ordering/manifest-extradeps.yaml
internal/testdata/ordering/one-ordered-policy.yaml
internal/testdata/ordering/override-dependencies.yaml
internal/testdata/ordering/policy-extradeps.yaml
internal/testdata/ordering/policy-level-dependencies.yaml
internal/testdata/ordering/three-ordered-manifests.yaml
internal/testdata/ordering/two-ordered-policies.yaml

Followup to:
- #148 
ref: https://issues.redhat.com/browse/ACM-9871

Add `unavailable` toleration to Placement

---

internal/plugin.go
internal/plugin_config_test.go
internal/plugin_test.go

This change will allow placements to override placementrule defaults and vice versa.
ref: https://issues.redhat.com/browse/ACM-10152

Allow override across different placement types

---

examples/policyGenerator.yaml

Fix policy name in example

---

docs/policygenerator-reference.yaml
internal/plugin.go
internal/plugin_test.go
internal/types/types.go
internal/utils.go

This supersedes #176 and the tests were taken from there also.
Relates:
https://issues.redhat.com/browse/ACM-13134

Add setting custom messages on configuration policies

---

.ci-operator.yaml
go.mod

ref: https://issues.redhat.com/browse/ACM-14251

Update to Go v1.22

---

build/common/Makefile.common.mk
build/common/config/.golangci.yml
go.mod
internal/expanders/expanders_utils_test.go
internal/expanders/gatekeeper.go
internal/expanders/gatekeeper_test.go
internal/expanders/kyverno.go
internal/expanders/kyverno_test.go
internal/patches.go
internal/patches_test.go
internal/plugin.go
internal/plugin_config_test.go
internal/plugin_test.go
internal/types/types.go
internal/typohelper_test.go
internal/utils.go
internal/utils_test.go

- Upgrade golangci-lint to 1.64.8
-  gosec => 2.22.2 kustomize => 5.6.
- Upgrade go to 1.23

Upgrade golangci-lint to 1.64.8
