- internal/plugin.go
This was returning the index instead of the array value.
> Fix faulty binding logic

- internal/plugin.go
- internal/plugin_config_test.go
- internal/plugin_test.go
Rather than running an initial validation on the `placementBindingDefaults.name`, this moves the logic deeper, leveraging the new placement flows to determine whether a default binding name is strictly necessary.
> Make default binding name optional

- cmd/main.go
`os.ReadFile` is not available in Go 1.15, and this is required to build
on top of the UBI8 container image.
> Add support for Go v1.15

- .gitignore
- docs/policygenerator-reference.yaml
- examples/input3/kyverno.yaml
- examples/policyGenerator.yaml
- internal/expanders/expanders.go
- internal/expanders/kyverno.go
- internal/expanders/test_kyverno.go
- internal/plugin.go
- internal/plugin_config_test.go
- internal/plugin_test.go
- internal/types/types.go
- internal/utils.go
- internal/utils_test.go
By default, when a manifest includes a Kyverno policy, an additional
configuration policy will get generated to inform on Kyverno policy
violations in Open Cluster Management.
Additionally, remediation action is no longer set at the root policy level.
This allows the policy generator to have granular control of the
remediation action of configuration policies it may automatically
generator on behalf of the user (i.e. Kyverno policy reporting).
> Add support for automatically informing on Kyverno policy violations

- .gitignore
- Makefile
This resolves the issue on some systems that get the error:
PolicyGenerator: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by PolicyGenerator)
Signed-off-by: mprahl <mprahl@users.noreply.github.com>
> Build the release binaries statically

- cmd/main.go
- docs/policygenerator-reference.yaml
- internal/plugin.go
- internal/plugin_config_test.go
- internal/plugin_test.go
- internal/utils.go
- internal/utils_test.go
This is an added security measure so that the user cannot specify a
manifest path that is not related to their Kustomize configuration.
Relates:
https://github.com/open-cluster-management/backlog/issues/18236
> Restrict manifest paths to be in the kustomize directory tree

- README.md
- docs/policygenerator-reference.yaml
- docs/policygenerator.md
- examples/input/placement.yaml
- examples/policyGenerator.yaml
- internal/plugin.go
- internal/plugin_config_test.go
- internal/plugin_test.go
- internal/types/types.go
- internal/utils.go
- internal/utils_test.go
Sync changes from:
- https://github.com/open-cluster-management-io/ocm-kustomize-generator-plugins/pull/3
I may need to look at it more in-depth to make sure the logic flows work, but I think it boils down to this one-line change that did it (it was formerly checking for `plCount.plr != 0`), and it appears to work:
```go
p.usingPlR = plCount.plc == 0
```
> Implement the Placement API

- docs/policygenerator-reference.yaml
- examples/policyGenerator.yaml
- internal/plugin.go
- internal/plugin_test.go
- internal/types/types.go
https://github.com/stolostron/backlog/issues/19412
Implement logic to generate policysets. There are three ways to generate
1. use policyDefaults.policysets field. If specified, any policies
without override will be included in the policysets
2. use policies[*].policysets field to include current policy in the
policysets. If specified, it overrides the policyDefaults.policysets
3. use policysets field. This allows you specify any policies no matter
policies are generated by generator or pre-exsit on hub. This field also
allows you specify the description of the policyset.
> Add policyset generation support

- examples/policyGenerator.yaml
- internal/plugin.go
- internal/plugin_test.go
https://github.com/stolostron/backlog/issues/19413
Refactor `createPlacement` and `createPlacementBinding` methods to
generate placement and placement binding when policy sets are defined.
> Add placement generation for policy sets

- internal/plugin.go
- internal/plugin_test.go
https://github.com/stolostron/backlog/issues/19644
Policyset placement was not counted in config validation which was causing
placement to be generated by default
> Count policyset placement and validate config

- internal/plugin.go
- internal/plugin_config_test.go
- internal/plugin_test.go
https://github.com/stolostron/backlog/issues/19644
Fix the issue that policyset name could be duplicated.
Add test cases for policyset config validation.
> Ensure policyset name is unique

- docs/policygenerator-reference.yaml
- examples/input-policy-type/iam.yaml
- examples/policyGenerator.yaml
- internal/plugin_config_test.go
- internal/plugin_test.go
- internal/utils.go
- internal/utils_test.go
Signed-off-by: Chunxi Luo <chuluo@redhat.com>
https://github.com/stolostron/backlog/issues/19466
In the test cases I only used IAM examples, Certificate should be similar since they are directly used as policy-template and I can also add Certificate and other examples in the test cases if needed.
> Support policy type manifest 

- docs/policygenerator-reference.yaml
- internal/plugin.go
- internal/plugin_config_test.go
- internal/plugin_test.go
- internal/types/types.go
- internal/utils.go
- internal/utils_test.go
https://github.com/stolostron/backlog/issues/19517
Signed-off-by: Chunxi Luo <chuluo@redhat.com>
> Add-support-for-the-metadataComplianceType-field

- cmd/main.go
- go.mod
- internal/expanders/expanders.go
- internal/expanders/gatekeeper.go
- internal/expanders/gatekeeper_test.go
- internal/expanders/kyverno.go
- internal/expanders/kyverno_test.go
- internal/patches.go
- internal/plugin.go
- internal/plugin_config_test.go
- internal/plugin_test.go
- internal/utils.go
- internal/utils_test.go
This will significantly reduce merge conflicts when syncing upstream to
Stolostron. It will also reduce the overhead of maintaining the
difference.
This also fixes some linting errors.
Related:
https://github.com/stolostron/backlog/issues/21790
> Rename the module name to match upstream

- docs/policygenerator-reference.yaml
- internal/plugin.go
- internal/plugin_config_test.go
- internal/types/types.go
Signed-off-by: Will Kutler <wkutler@redhat.com>
https://github.com/stolostron/backlog/issues/22350
> Add support for policyDefaults.disabled

- docs/policygenerator-reference.yaml
- internal/plugin.go
- internal/plugin_config_test.go
- internal/plugin_test.go
- internal/types/types.go
This allows managing all Placements/PlacementRules in the ACM hub separate from the generated policies that use them.
Fixes #50 
Example usage available at https://github.com/brian-jarvis/test-placement/tree/reuse-placement
Signed-off-by: Brian Jarvis <bjarvis@redhat.com>
> Add ability to specify the name of an existing Placement or PlacementRule

- internal/plugin.go
- internal/plugin_test.go
It is not a best practice to have this set for policies since a policy
should still be applied to unhealthy clusters.
> Remove the cluster conditions added to the placement rule

- go.mod
- internal/plugin.go
- internal/typohelper.go
- internal/typohelper_test.go
When the input configuration does not match the schema in the go type,
the generator will now respond with an error. The intention is to help
users when there is a typo in the configuration, which otherwise would
just be ignored (and in the case of a map, any configuration "inside"
would be dropped).
This also adds help text to these error cases, to try and identify what
field the user might have meant. That implementation uses a library
which does not compute the Levenshtein distance, but should work well
enough, and has the advantage of already being in the import graph.
Refs:
- https://github.com/stolostron/backlog/issues/19646
Signed-off-by: Justin Kulikauskas <jkulikau@redhat.com>
> Fail generation and add help on field typos

- docs/policygenerator-reference.yaml
- internal/plugin.go
- internal/plugin_config_test.go
- internal/plugin_test.go
- internal/types/types.go
- internal/utils.go
- internal/utils_test.go
I was uncertain whether the value should be validated. I didn't validate it since other string fields in the generator (like `complianceType` and `remediationAction`) didn't appear to have validation in place.
Addresses:
- https://github.com/stolostron/backlog/issues/25353
> Support `PruneObjectBehavior`

- Makefile
`go-get-tool` was already implemented, so this completes the issue with addition of a `clean` target
ref: https://github.com/stolostron/backlog/issues/23044
> Add `clean` Make target

- docs/policygenerator-reference.yaml
- internal/expanders/gatekeeper_test.go
- internal/expanders/kyverno_test.go
- internal/plugin.go
- internal/plugin_config_test.go
- internal/plugin_test.go
- internal/types/types.go
- internal/utils.go
- internal/utils_test.go
This PR is twofold:
- Implement `PolicyOptions` and `ConfigurationPolicyOptions`, which folds keys into a single struct that can be used in the `PolicyDefaults`, `Policy`, and `Manifests` structs.
- The consolidation brings consistency to overrides in `Manifests` that was missing previously, so this also adds the required validation and overrides there
> Consolidate structs / Consistent `manifests` overrides

- internal/expanders/gatekeeper.go
- internal/expanders/gatekeeper_test.go
This was accidentally checking for annotations in the format of an array of maps but it should just be a map.
Signed-off-by: mprahl <mprahl@users.noreply.github.com>
> Fix the Gatekeeper expander event inform policy

- cmd/main.go
- docs/policygenerator-reference.yaml
- internal/plugin.go
- internal/plugin_config_test.go
- internal/plugin_test.go
- internal/types/types.go
- internal/utils.go
- internal/utils_test.go
The new `dependencies` field in the generator is the same as the new `dependencies` field in the Policy type, however, more fields are optional and will be filled in by the generator with useful defaults.
The new `ignorePending` field is also the same, but since that would be set on templates, and the generator does not expose much at the template level, here the field is set on the policy, and the generator sets the correct field in all the templates of that policy. For a similar reason, the `extraDependencies` field is not exposed in the generator at all.
The new `orderViaDependencies` field will set up a chain of dependencies on the created policies. So if 3 policies are created by the generator, policy 2 will depend on policy 1, and policy 3 will depend on policy 2.
In all cases, …
> Add options for policy ordering

- go.mod
- internal/plugin.go
- internal/testdata/ordering/three-ordered-manifests.yaml
- internal/utils.go
- internal/utils_test.go
Some fixes to the policy ordering feature after an end-to-end demo exposed some problems. More details in each commit.
> Fix order manifests

- docs/policygenerator-reference.yaml
- internal/plugin.go
- internal/plugin_config_test.go
- internal/plugin_test.go
- internal/types/types.go
When Policies are generated separately from PolicySets, it may be desirable to only generate the Policies and not the placement manifests.
Closes #86
> Allow placement generation to be shut off

- docs/policygenerator-reference.yaml
- internal/plugin.go
- internal/plugin_config_test.go
- internal/plugin_test.go
- internal/types/types.go
Placements can now be generated by nesting a full labelSelector or clusterSelector YAML under the `placement` key, in addition to the legacy method of listing key/value pairs under `placement`. This allows users to specify multiple clusters in the values array of a placement or placementRule, and to use matchLabels instead of matchExpressions (only supported by placement).
Signed-off-by: Will Kutler <wkutler@redhat.com>
> Add support for generating placement with raw data

- docs/policygenerator-reference.yaml
- internal/plugin_config_test.go
- internal/plugin_test.go
- internal/utils.go
- internal/utils_test.go
When `informGatekeeperPolicies` is set to `false`, wrap Gatekeeper manifests directly in a Policy rather than in a ConfigurationPolicy.
ref: https://issues.redhat.com/browse/ACM-4438
Additionally, I've noticed some cases where a Policy was being wrapped in a Policy by the generator, causing confusion. I added a commit here to throw an error in this case.
> Wrap Gatekeeper manifests directly when expander is disabled

- internal/plugin_test.go
- internal/utils.go
- internal/utils_test.go
Fixes when `informGatekeeperPolicies` is set to `true`, the Gatekeeper manifests are correctly wrapped in a ConfigurationPolicy.
ref: https://issues.redhat.com/browse/ACM-4438
> Fix Gatekeeper manifest wrapping

- internal/ordering_test.go
- internal/testdata/ordering/default-extradeps-consolidated.yaml
- internal/testdata/ordering/ignore-pending-policy-consolidated.yaml
- internal/utils.go
A call to `setTemplateOptions()` was missed, causing consolidated manifests to not have `ignorePending` set properly (and `extraDependencies` is also affected).
ref: https://issues.redhat.com/browse/ACM-6163
> Fix `ignorePending` when manifests are consolidated

- Makefile
- cmd/PolicyGenerator/main.go
Adds a generator version flag with the Git SHA in the output:
```
v1.12.2-ab49eaf2a21d44265784bbd1f8381ec6e8928828
```
Also adds verification that the `VERSION.txt` file was updated so that a release isn't created without the version being updated.
This is my first time adding version information to anything, so if anyone has other ideas/pointers, do share!
ref: https://issues.redhat.com/browse/ACM-5803
Closes https://github.com/open-cluster-management-io/policy-generator-plugin/issues/118
> Add version flag to generator

- Makefile
Followup to:
- #120 
ref: https://github.com/open-cluster-management-io/policy-generator-plugin/issues/118
ref: https://issues.redhat.com/browse/ACM-5803
> Don't set version if SHA is empty

- Makefile
- cmd/PolicyGenerator/main.go
Using `go install` resulted in `Unversioned binary`, which didn't seem ideal. This allows us to set the version a build time (which is preferred for our ACM use cases) but also falls back to the Go determined module version when using `go install`, which is also a nice fallback. Here I tagged this branch and it retrieves the version as:
```
$ PolicyGenerator --version
v0.0.0-20230719194345-c518eac8081d
```
Followup to:
- #120
- #121
ref: https://issues.redhat.com/browse/ACM-5803
> Fetch build version if version wasn't set a build time

- .github/workflows/release.yml
- Makefile
- cmd/PolicyGenerator/main.go
`actions/checkout` creates a lightweight tag, so we need to force a fetch to retrieve the annotated one.
Followup to:
- #122 
- #121 
- #120 
ref: https://issues.redhat.com/browse/ACM-5803
> Fetch annotated tag

- internal/ordering_test.go
- internal/plugin.go
- internal/testdata/ordering/manifest-extradeps-configpolicy.yaml
IamPolicy, CertificatePolicy, and ConfigurationPolicy should not have a namespace set.
ref: https://issues.redhat.com/browse/ACM-7353
Followup to:
- #126 
/cc @JustinKuli @mprahl
> Only set the dependency namespace for Policy

- internal/plugin.go
- internal/plugin_test.go
- internal/utils.go
- internal/utils_test.go
For policy-templates entries that are not OCM policies, it is supported to set the `policy.open-cluster-management.io/severity` annotation for other tooling to determine the severity of a noncompliant event. This adds that automatically.
Relates:
https://issues.redhat.com/browse/ACM-6860
> Set the severity annotation for non-OCM policies

- internal/ordering_test.go
- internal/plugin.go
- internal/testdata/ordering/manifest-extradeps-configpolicy-defaults.yaml
- Fix severity set at the manifest level
- Fix setting manifest overrides correctly
-  _Since the manifest configuration wasn't being set when consolidateManifests was true, it wasn't being propagated to things like expanded policies and policy template manifests provided directly. This fixes it to set manifest configurations and then compare manifest and policy configurations to make sure they match when consolidateManifests is true._
ref: https://issues.redhat.com/browse/ACM-9131
> Fix setting manifest configurations

- docs/policygenerator-reference.yaml
- internal/plugin.go
- internal/plugin_test.go
- internal/testdata/ordering/default-deps-propagated.yaml
- internal/testdata/ordering/default-extradeps-consolidated.yaml
- internal/testdata/ordering/default-extradeps-override.yaml
- internal/testdata/ordering/default-extradeps-propagated.yaml
- internal/testdata/ordering/dependency-details-config.yaml
- internal/testdata/ordering/extradeps-overrides.yaml
- internal/testdata/ordering/ignore-pending-manifest-override.yaml
- internal/testdata/ordering/ignore-pending-policy-consolidated.yaml
- internal/testdata/ordering/ignore-pending-policy-override.yaml
- internal/testdata/ordering/ignore-pending-propagation.yaml
- internal/testdata/ordering/manifest-extradeps-configpolicy-defaults.yaml
- internal/testdata/ordering/manifest-extradeps-configpolicy.yaml
- internal/testdata/ordering/manifest-extradeps.yaml
- internal/testdata/ordering/one-ordered-policy.yaml
- internal/testdata/ordering/override-dependencies.yaml
- internal/testdata/ordering/policy-extradeps.yaml
- internal/testdata/ordering/policy-level-dependencies.yaml
- internal/testdata/ordering/three-ordered-manifests.yaml
- internal/testdata/ordering/two-ordered-policies.yaml
- internal/types/types.go
Adds description field to PolicyOptions.  And sets the default value if not defined in the PolicyGenerator.
https://issues.redhat.com/browse/ACM-9080
> Allow setting policy open-cluster-management.io/description annoation

- internal/utils.go
- internal/utils_test.go
When all ConfigurationPolicies have `RemediationAction` `InformOnly`, the root Policy is also set to have `RemediationAction` `InformOnly`. However, `InformOnly` is not valid on a Policy, and was thus modified to be set to `inform` in this case.
> Fix PolicyGenerator setting InformOnly on root policy

- docs/policygenerator-reference.yaml
- examples/input-object-templates-raw/object-templates-raw.yaml
- examples/policyGenerator.yaml
- internal/ordering_test.go
- internal/plugin_config_test.go
- internal/plugin_test.go
- internal/testdata/ordering/default-extradeps-object-templates-raw.yaml
- internal/testdata/ordering/ignore-pending-object-templates-raw.yaml
- internal/utils.go
- internal/utils_test.go
Adds support for manifest files with only object-templates-raw field, which gets put into a ConfigurationPolicy.
Ref: https://issues.redhat.com/browse/ACM-10565
> Add support for object-templates-raw

- docs/policygenerator-reference.yaml
- internal/plugin.go
- internal/plugin_test.go
- internal/types/types.go
- internal/utils.go
The second commit updates the recordDiff field based on the new behavior.
> Add the recreateOption field

- README.md
- internal/testdata/helm/Chart.yaml
- internal/testdata/helm/index.yaml
- internal/testdata/helm/templates/_helpers.tpl
- internal/testdata/helm/templates/serviceaccount.yaml
- internal/testdata/helm/values.yaml
- internal/utils.go
- internal/utils_test.go
The user may set POLICY_GEN_DISABLE_LOAD_RESTRICTORS=true to disable the Kustomize load restrictions when the manifest is a Kustomize directory. This is off by default.
> Add support for disabling load restrictions for executing kustomize

- docs/policygenerator-reference.yaml
- internal/plugin.go
- internal/plugin_test.go
- internal/types/types.go
- internal/utils.go
- Add a new field of `gatekeeperEnforcementAction`
- Default value of the field is unset and when unset, don't touch the constraint (existing behavior) 
- If set, then directly set `spec.enforcementAction` in the Gatekeeper constraint 
- Should be settable at the policyDefaults, policy, and manifest levels (i.e. like the `ConfigurationPolicyOptions` struct).
Ref: https://issues.redhat.com/browse/ACM-11076
Signed-off-by: yiraeChristineKim <yikim@redhat.com>
> Add new field gatekeeperEnforcementAction to override enforcementAction

- internal/plugin_config_test.go
- internal/utils.go
- internal/utils_test.go
Fixes when one of our policy types is provided and specifies a namespace (either directly or through an embedded Kustomize namespace transformer).
ref: https://issues.redhat.com/browse/ACM-8839
> Fix: Clean namespaces from Policy types

- docs/policygenerator-reference.yaml
- internal/ordering_test.go
- internal/testdata/ordering/manifest-level-name-raw-consolidate-false.yaml
- internal/testdata/ordering/manifest-level-name-raw-consolidate-true.yaml
- internal/testdata/ordering/manifest-level-name.yaml
- internal/types/types.go
- internal/utils.go
When creating a policy with multiple manifests and `consolidateManfifest: false` the generated ConfigurationPolicies are names after the Policy with an index appended.
This causes issues when attempting to use extraDependencies such as below.  Adding an additional manifest will change the index causing the existing dependencies to be incorrect.
Allowing setting the name would also make it easier to identify in the UI when reviewing a policy.
Ref: https://issues.redhat.com/browse/ACM-12563
> Add setting name on ConfigurationPolicy

- docs/policygenerator-reference.yaml
- internal/ordering_test.go
- internal/testdata/ordering/manifest-extradeps-configpolicy.yaml
- internal/testdata/ordering/manifest-level-name-raw-consolidate-true.yaml
- internal/utils.go
This PR supports the more complex cases of setting names. Especially, `consolidateManifests` is true and the `manifest-path name` is present.
https://issues.redhat.com/browse/ACM-1256
> Refactor name setting for complex cases

- internal/ordering_test.go
- internal/testdata/ordering/manifest-level-name-raw-consolidate-true-empty-name.yaml
- internal/testdata/ordering/manifest-level-name-raw-consolidate-true-with-name.yaml
- internal/utils.go
There is a bug when `raw-template`  manifest is ahead of `obj-template` manifest.
https://issues.redhat.com/browse/ACM-12563
> Fix the bug where raw is abead of obj-temp 

- docs/policygenerator-reference.yaml
- internal/plugin.go
- internal/plugin_test.go
- internal/types/types.go
Relates:
https://issues.redhat.com/browse/ACM-13608
> Add support for spec.hubTemplateOptions when generating a policy

- go.mod
Not sure how this even got in here (it was me 🤷‍♂️ ) , but it's breaking `go install` and it seems to work without it.
> Remove `replace` from `go.mod`

- Makefile
Required for Konflux (the other option is to add `go mod vendor` somewhere, but I think this ought to suffice)
> Add `-mod=readonly` to build

- Makefile
Since the loop is technically working, it doesn't short-circuit Make.
> Exit loop on build errors

- internal/plugin.go
- internal/plugin_config_test.go
Policy generator plugin does not allow evaluationInterval to be set to "watch". The policy generator should generate policy successfully with "watch"
Ref: https://issues.redhat.com/browse/ACM-17774
Signed-off-by: yiraeChristineKim <yikim@redhat.com>
> 🐛 [Bug]Fix evaluationInterval 'watch' bug

- docs/policygenerator-reference.yaml
- internal/plugin.go
- internal/plugin_test.go
- internal/types/types.go
- internal/utils.go
ref: https://issues.redhat.com/browse/ACM-18011
> Add `objectSelector`

- cmd/PolicyGenerator/main.go
When the help command is not implemented, pflag returns the message `help requested` and an exit code of 2.
This PR returns an exit code of 0 after running the help command.
ref: https://issues.redhat.com/browse/ACM-21054
```
$ make build-binary
$ ./PolicyGenerator -h
Usage: PolicyGenerator [flags] <policy-generator-config-file>...
--debug     Print the stack trace with error messages
-h, --help      Print the help message
--version   Print the version of the generator
$ echo $?
0
$ ./PolicyGenerator --help
Usage: PolicyGenerator [flags] <policy-generator-config-file>...
--debug     Print the stack trace with error messages
-h, --help      Print the help message
--version   Print the version of the generator
$ echo $?
0
```
> Fix cli help flag return code
